service: cvs-tsk-authoriser

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
provider:
  region: eu-west-1
  name: aws
  runtime: nodejs16.x
  timeout: 60

functions:
  authoriserFunction:
    handler: src/handler.handler
  testFunction:
    handler: tests/handler.test
    events:
      - http:
          path: testFunction
          method: POST
          authorizer: authoriserFunction
